<?php return array (
  'create' => 'create',
  'main_image' => 'main_image',
  'update' => 'update',
  'time_data' => 'time_data',
  'date_at' => 'date_at',
  'publisher' => 'publisher',
  'mainData' => 'mainData',
  'title' => 'title',
  'details' => 'details',
  'features' => 'features',
  'location' => 'location',
  'location_map' => 'location_map',
  'images' => 'images',
  'Action' => 'Action',
  'ID' => 'ID',
  'district' => 'district',
  'city' => 'city',
);