<?php return array (
  'Cars Brands' => 'Cars Brands',
  'Brand Name' => 'Brand Name',
  'Add Car Brand' => 'Add Car Brand',
  'Save Changes' => 'Save Changes',
  'Close' => 'Close',
  'Add City' => 'Add City',
  'City Name' => 'City Name',
  'Update Car Brand' => 'Update Car Brand',
  'Actions' => 'Actions',
  'Edit' => 'Edit',
  'Delete' => 'Delete',
  'Search City Name' => 'Search City Name',
  'Update City' => 'Update City',
  'Search Groups' => 'Search Groups',
  'Add Group Type' => 'Add Group Type',
  '' => '',
  'Add_City' => 'Add_City',
  'City_Name' => 'City_Name',
  'Save_Changes' => 'Save_Changes',
  'cities' => 'cities',
  'Update_City' => 'Update_City',
  'Add_district_name' => 'Add_district_name',
  'district_name' => 'district_name',
  'Add' => 'Add',
  'update_district_name' => 'update_district_name',
);