<?php return array (
  'area' => 'المنطقة',
  'buss_type' => 'نوع العمل',
  'create' => 'اضافة مشروع',
  'details' => 'التفاصيل',
  'images' => 'صور المشروع',
  'impl_date' => 'تاريخ التنفيذ',
  'impl_period' => 'فترة التنفيذ',
  'location' => 'الموقع',
  'location_data' => 'بيانات الموقع',
  'mainData' => 'البيانات الاساسية',
  'time_data' => 'time_data',
  'title' => 'اسم المشروع',
  'publisher' => 'المطور',
  'date_at' => 'تاريخ',
  'city' => 'الدولة ',
  'district' => 'المدينة',
  'features' => 'المميزات',
);
