<?php

return array (
  'Add_Users' => 'اضافة مستخدم',
  'All_Users' => 'كل المستخدمين',
  'Surveys' => 'الجهات الداعمة لريادة الأعمال',
  'Users' => 'المستخدمين',
  'Users_Settings' => 'المستخدمين',
  'about' => 'من نحن',
  'advantages' => 'مميزتنا',
  'banner' => 'البانر',
  'blog' => 'الاخبار',
  'car' => 'انواع السيارات',
  'city' => 'المحافظات',
  'client' => 'العملاء',
  'contact' => 'الرسائل',
  'district' => 'المدن',
  'entity' => 'الجهات الداعمة',
  'event' => 'الفاعليات',
  'feedback' => 'اراء العملاء',
  'gallery' => 'الاستويو',
  'group' => 'تصنيف المجموعات',
  'groupsapp' => 'الجروبات',
  'mdata' => 'بيانات الموقع ',
  'mobile_app' => 'بيانات التطبيق ',
  'partner' => 'الشركاء',
  'projects' => 'المشاريع',
  'roles' => 'ادوار الصلاحية',
  'service' => 'مراكز التمويل ',
  'site_data' => 'بيانات الموقع ',
  'site_setting' => 'اعدادات الموقع',
  'statistics' => 'الاحصائيات',
  'stetting' => 'الاعدادات',
  'store_management' => 'ادارة الموقع',
  'teacher' => 'المعلمين',
  'training_centers' => 'مراكز التدريب ',
  'tripsapp' => 'الرحلات',
  'videos' => 'مكتبة الفديوهات',
  'web_site' => 'ادارة الموقع',
  'web_site_pages' => 'صفحات الموقع',
);
